# Generated by Django 5.1.15 on 2026-02-17 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='ปีงบประมาณ')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่ม')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุด')),
                ('is_active', models.BooleanField(default=False, verbose_name='ใช้งานอยู่')),
            ],
            options={
                'verbose_name': 'ปีงบประมาณ',
                'verbose_name_plural': 'ปีงบประมาณ',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True, verbose_name='รหัสโครงการ')),
                ('name', models.CharField(max_length=300, verbose_name='ชื่อโครงการ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='งบประมาณรวม')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่ม')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุด')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('active', 'ดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='draft', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.department', verbose_name='หน่วยงาน')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.fiscalyear', verbose_name='ปีงบประมาณ')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ')),
            ],
            options={
                'verbose_name': 'โครงการ',
                'verbose_name_plural': 'โครงการ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_number', models.PositiveIntegerField(verbose_name='ลำดับกิจกรรม')),
                ('name', models.CharField(max_length=300, verbose_name='ชื่อกิจกรรม')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='งบประมาณที่จัดสรร')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่ม')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุด')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=12, verbose_name='สถานะ')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_activities', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project', verbose_name='โครงการ')),
            ],
            options={
                'verbose_name': 'กิจกรรม',
                'verbose_name_plural': 'กิจกรรม',
                'ordering': ['project', 'activity_number'],
                'unique_together': {('project', 'activity_number')},
            },
        ),
    ]
