# Generated by Django 5.1.15 on 2026-02-17 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notify_persons',
            field=models.ManyToManyField(blank=True, related_name='notify_activities', to=settings.AUTH_USER_MODEL, verbose_name='ตั้งแจ้งเตือน'),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible_persons',
            field=models.ManyToManyField(blank=True, related_name='responsible_activities', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบกิจกรรม'),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_persons',
            field=models.ManyToManyField(blank=True, related_name='notify_projects', to=settings.AUTH_USER_MODEL, verbose_name='ตั้งแจ้งเตือน'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible_persons',
            field=models.ManyToManyField(blank=True, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบหลัก'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_activities_old', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ (เดิม)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_projects_old', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ (เดิม)'),
        ),
    ]
