# Generated by Django 5.1.15 on 2026-02-17 08:03

from django.db import migrations


def copy_fk_to_m2m(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Activity = apps.get_model('projects', 'Activity')

    for project in Project.objects.all():
        if project.responsible_person_id:
            project.responsible_persons.add(project.responsible_person_id)
            project.notify_persons.add(project.responsible_person_id)

    for activity in Activity.objects.all():
        if activity.responsible_person_id:
            activity.responsible_persons.add(activity.responsible_person_id)
            activity.notify_persons.add(activity.responsible_person_id)


def copy_m2m_to_fk(apps, schema_editor):
    """Reverse: copy first M2M entry back to FK."""
    Project = apps.get_model('projects', 'Project')
    Activity = apps.get_model('projects', 'Activity')

    for project in Project.objects.all():
        first = project.responsible_persons.first()
        if first:
            project.responsible_person_id = first.pk
            project.save(update_fields=['responsible_person_id'])

    for activity in Activity.objects.all():
        first = activity.responsible_persons.first()
        if first:
            activity.responsible_person_id = first.pk
            activity.save(update_fields=['responsible_person_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_m2m_responsible_notify'),
    ]

    operations = [
        migrations.RunPython(copy_fk_to_m2m, copy_m2m_to_fk),
    ]
