# Generated by Django 5.1.15 on 2026-02-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_copy_fk_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsible_person',
        ),
    ]
