# Generated by Django 5.1.15 on 2026-02-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_organization_field'),
        ('projects', '0004_remove_fk_responsible_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.department', verbose_name='แผนก'),
        ),
    ]
