# Generated by Django 5.1.15 on 2026-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_department_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='projects/documents/', verbose_name='เอกสารแนบ (PDF)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'ร่าง'), ('not_started', 'ยังไม่ดำเนินการ'), ('active', 'ดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='draft', max_length=20, verbose_name='สถานะ'),
        ),
    ]
