# Generated by Django 5.1.15 on 2026-02-18 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_document_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='เหตุผลที่ขอลบ')),
                ('status', models.CharField(choices=[('pending', 'รอพิจารณา'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='ขอเมื่อ')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='พิจารณาเมื่อ')),
                ('review_remark', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to='projects.project', verbose_name='โครงการ')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอลบ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้พิจารณา')),
            ],
            options={
                'verbose_name': 'คำขอลบโครงการ',
                'verbose_name_plural': 'คำขอลบโครงการ',
                'ordering': ['-requested_at'],
            },
        ),
    ]
