# Generated by Django 5.1.15 on 2026-02-23 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectdeleterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='budget_accumulated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินสะสม'),
        ),
        migrations.AddField(
            model_name='activity',
            name='budget_government',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินแผ่นดิน'),
        ),
        migrations.AddField(
            model_name='activity',
            name='budget_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินรายได้'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='งบประมาณที่จัดสรร (รวม)'),
        ),
        migrations.CreateModel(
            name='ProjectBudgetSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('government', 'เงินแผ่นดิน'), ('accumulated', 'เงินสะสม'), ('revenue', 'เงินรายได้')], max_length=20, verbose_name='หมวดเงิน')),
                ('erp_code', models.CharField(blank=True, max_length=50, verbose_name='รหัสโครงการ ERP')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='งบประมาณ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_sources', to='projects.project', verbose_name='โครงการ')),
            ],
            options={
                'verbose_name': 'แหล่งงบประมาณ',
                'verbose_name_plural': 'แหล่งงบประมาณ',
                'ordering': ['source_type'],
                'unique_together': {('project', 'source_type')},
            },
        ),
    ]
