# Generated by Django 5.1.15 on 2026-02-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_activity_budget_accumulated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='no_budget',
            field=models.BooleanField(default=False, verbose_name='ไม่ใช้งบประมาณ'),
        ),
    ]
