# Generated by Django 5.1.15 on 2026-02-23 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_activity_no_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='ครั้งที่')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ/ชื่อครั้งนี้')),
                ('date', models.DateField(verbose_name='วันที่จัดกิจกรรม')),
                ('description', models.TextField(blank=True, verbose_name='สรุปผลการจัด')),
                ('document', models.FileField(blank=True, null=True, upload_to='activities/reports/', verbose_name='เอกสารรายงาน (PDF/รูปภาพ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.activity', verbose_name='กิจกรรม')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activity_reports', to=settings.AUTH_USER_MODEL, verbose_name='บันทึกโดย')),
            ],
            options={
                'verbose_name': 'รายงานกิจกรรมย่อย',
                'verbose_name_plural': 'รายงานกิจกรรมย่อย',
                'ordering': ['activity', 'round_number'],
                'unique_together': {('activity', 'round_number')},
            },
        ),
    ]
