# Generated by Django 5.1.15 on 2026-05-14 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_activityreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อแบบฟอร์ม')),
                ('category', models.CharField(choices=[('activity_report', 'รายงานผลกิจกรรม'), ('expense', 'เอกสารเบิกจ่าย'), ('project', 'เอกสารโครงการ'), ('other', 'อื่นๆ')], default='other', max_length=20, verbose_name='หมวดหมู่')),
                ('file', models.FileField(upload_to='doc_templates/', verbose_name='ไฟล์')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย/วิธีใช้')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='เวอร์ชัน/ปีงบ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='อัปโหลดเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_doc_templates', to=settings.AUTH_USER_MODEL, verbose_name='อัปโหลดโดย')),
            ],
            options={
                'verbose_name': 'แบบฟอร์ม',
                'verbose_name_plural': 'แบบฟอร์ม',
                'ordering': ['category', 'name'],
            },
        ),
    ]
