# Generated by Django 5.1.15 on 2026-02-17 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อหน่วยงาน')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสหน่วยงาน')),
            ],
            options={
                'verbose_name': 'หน่วยงาน',
                'verbose_name_plural': 'หน่วยงาน',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'เจ้าหน้าที่'), ('planner', 'เจ้าหน้าที่แผน'), ('head', 'หัวหน้างาน'), ('admin', 'ผู้ดูแลระบบ')], default='staff', max_length=10, verbose_name='บทบาท')),
                ('line_user_id', models.CharField(blank=True, max_length=50, verbose_name='LINE User ID')),
                ('notify_budget_alert', models.BooleanField(default=True, verbose_name='แจ้งเตือนงบประมาณ')),
                ('notify_deadline', models.BooleanField(default=True, verbose_name='แจ้งเตือนกำหนดส่ง')),
                ('budget_threshold', models.PositiveIntegerField(default=80, verbose_name='เกณฑ์แจ้งเตือนงบ (%)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department', verbose_name='หน่วยงาน')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้',
            },
        ),
    ]
