# Generated by Django 5.1.15 on 2026-02-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_npu_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ซิงค์ล่าสุด'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='npu_citizen_id',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='เลขบัตรประชาชน'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='npu_staff_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='รหัสบุคลากร NPU'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='ตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='source',
            field=models.CharField(choices=[('manual', 'สร้างในระบบ'), ('npu_api', 'NPU AD')], default='manual', max_length=10, verbose_name='แหล่งข้อมูล'),
        ),
    ]
