# Generated by Django 5.1.15 on 2026-02-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_npu_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='สถานะการปฏิบัติงาน'),
        ),
    ]
