# Generated by Django 5.1.15 on 2026-02-17 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_employment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code'], 'verbose_name': 'แผนก', 'verbose_name_plural': 'แผนก'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, help_text='ดึงจาก NPU AD อัตโนมัติ', max_length=255, verbose_name='หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อแผนก'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department', verbose_name='แผนก'),
        ),
    ]
