# Generated by Django 5.1.15 on 2026-02-23 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_organization_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'เจ้าหน้าที่'), ('planner', 'เจ้าหน้าที่แผน'), ('head', 'หัวหน้าแผนก'), ('admin', 'ผู้ดูแลระบบ')], default='staff', max_length=10, verbose_name='บทบาท'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'เข้าสู่ระบบ'), ('LOGOUT', 'ออกจากระบบ'), ('LOGIN_FAILED', 'เข้าสู่ระบบล้มเหลว'), ('EXPENSE_APPROVE', 'อนุมัติรายการเบิกจ่าย'), ('EXPENSE_REJECT', 'ปฏิเสธรายการเบิกจ่าย'), ('PROJECT_CREATE', 'สร้างโครงการ'), ('PROJECT_UPDATE', 'แก้ไขโครงการ'), ('PROJECT_DELETE', 'ลบโครงการ'), ('PROJECT_STATUS', 'เปลี่ยนสถานะโครงการ'), ('PROJECT_DELETE_REQUEST', 'ขอลบโครงการ'), ('PROJECT_DELETE_APPROVE', 'อนุมัติลบโครงการ'), ('PROJECT_DELETE_REJECT', 'ปฏิเสธคำขอลบโครงการ'), ('ACTIVITY_CREATE', 'สร้างกิจกรรม'), ('ACTIVITY_UPDATE', 'แก้ไขกิจกรรม'), ('EXPENSE_CREATE', 'บันทึกรายการเบิกจ่าย'), ('EXPENSE_UPDATE', 'แก้ไขรายการเบิกจ่าย'), ('EXPENSE_DELETE', 'ลบรายการเบิกจ่าย'), ('USER_ROLE_CHANGE', 'เปลี่ยนบทบาทผู้ใช้'), ('USER_PASSWORD_RESET', 'รีเซ็ตรหัสผ่าน'), ('USER_SOURCE_CHANGE', 'เปลี่ยนแหล่งข้อมูลผู้ใช้'), ('USER_TOGGLE_ACTIVE', 'เปิด/ปิดการใช้งานผู้ใช้')], db_index=True, max_length=30, verbose_name='การกระทำ')),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important')], default='important', max_length=10, verbose_name='ระดับ')),
                ('target_repr', models.CharField(blank=True, max_length=500, verbose_name='เป้าหมาย')),
                ('detail', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลา')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_about', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้เป้าหมาย')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการ')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
