# Generated by Django 5.1.15 on 2026-02-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อหน่วยงาน')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='หมายเหตุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หน่วยงานที่อนุมัติอัตโนมัติ',
                'verbose_name_plural': 'หน่วยงานที่อนุมัติอัตโนมัติ',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'อนุมัติแล้ว'), ('pending', 'รอการอนุมัติ'), ('rejected', 'ปฏิเสธ')], default='approved', max_length=10, verbose_name='สถานะอนุมัติ'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'เข้าสู่ระบบ'), ('LOGOUT', 'ออกจากระบบ'), ('LOGIN_FAILED', 'เข้าสู่ระบบล้มเหลว'), ('EXPENSE_APPROVE', 'อนุมัติรายการเบิกจ่าย'), ('EXPENSE_REJECT', 'ปฏิเสธรายการเบิกจ่าย'), ('PROJECT_CREATE', 'สร้างโครงการ'), ('PROJECT_UPDATE', 'แก้ไขโครงการ'), ('PROJECT_DELETE', 'ลบโครงการ'), ('PROJECT_STATUS', 'เปลี่ยนสถานะโครงการ'), ('PROJECT_DELETE_REQUEST', 'ขอลบโครงการ'), ('PROJECT_DELETE_APPROVE', 'อนุมัติลบโครงการ'), ('PROJECT_DELETE_REJECT', 'ปฏิเสธคำขอลบโครงการ'), ('ACTIVITY_CREATE', 'สร้างกิจกรรม'), ('ACTIVITY_UPDATE', 'แก้ไขกิจกรรม'), ('EXPENSE_CREATE', 'บันทึกรายการเบิกจ่าย'), ('EXPENSE_UPDATE', 'แก้ไขรายการเบิกจ่าย'), ('EXPENSE_DELETE', 'ลบรายการเบิกจ่าย'), ('USER_ROLE_CHANGE', 'เปลี่ยนบทบาทผู้ใช้'), ('USER_PASSWORD_RESET', 'รีเซ็ตรหัสผ่าน'), ('USER_SOURCE_CHANGE', 'เปลี่ยนแหล่งข้อมูลผู้ใช้'), ('USER_TOGGLE_ACTIVE', 'เปิด/ปิดการใช้งานผู้ใช้'), ('USER_APPROVE', 'อนุมัติผู้ใช้'), ('USER_REJECT', 'ปฏิเสธผู้ใช้')], db_index=True, max_length=30, verbose_name='การกระทำ'),
        ),
    ]
