# Generated by Django 5.1.15 on 2026-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_approvedorganization_userprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'เข้าสู่ระบบ'), ('LOGOUT', 'ออกจากระบบ'), ('LOGIN_FAILED', 'เข้าสู่ระบบล้มเหลว'), ('EXPENSE_APPROVE', 'อนุมัติรายการเบิกจ่าย'), ('EXPENSE_REJECT', 'ปฏิเสธรายการเบิกจ่าย'), ('PROJECT_CREATE', 'สร้างโครงการ'), ('PROJECT_UPDATE', 'แก้ไขโครงการ'), ('PROJECT_DELETE', 'ลบโครงการ'), ('PROJECT_STATUS', 'เปลี่ยนสถานะโครงการ'), ('PROJECT_DELETE_REQUEST', 'ขอลบโครงการ'), ('PROJECT_DELETE_APPROVE', 'อนุมัติลบโครงการ'), ('PROJECT_DELETE_REJECT', 'ปฏิเสธคำขอลบโครงการ'), ('ACTIVITY_CREATE', 'สร้างกิจกรรม'), ('ACTIVITY_UPDATE', 'แก้ไขกิจกรรม'), ('EXPENSE_CREATE', 'บันทึกรายการเบิกจ่าย'), ('EXPENSE_UPDATE', 'แก้ไขรายการเบิกจ่าย'), ('EXPENSE_DELETE', 'ลบรายการเบิกจ่าย'), ('BUDGET_TRANSFER', 'โอนงบประมาณ'), ('USER_ROLE_CHANGE', 'เปลี่ยนบทบาทผู้ใช้'), ('USER_PASSWORD_RESET', 'รีเซ็ตรหัสผ่าน'), ('USER_SOURCE_CHANGE', 'เปลี่ยนแหล่งข้อมูลผู้ใช้'), ('USER_TOGGLE_ACTIVE', 'เปิด/ปิดการใช้งานผู้ใช้'), ('USER_APPROVE', 'อนุมัติผู้ใช้'), ('USER_REJECT', 'ปฏิเสธผู้ใช้')], db_index=True, max_length=30, verbose_name='การกระทำ'),
        ),
    ]
