# Generated by Django 5.1.15 on 2026-02-17 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='รายละเอียด')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนเงิน')),
                ('expense_date', models.DateField(verbose_name='วันที่เบิกจ่าย')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='เลขที่ใบเสร็จ')),
                ('status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติ'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='อนุมัติเมื่อ')),
                ('remark', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.activity', verbose_name='กิจกรรม')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='อนุมัติโดย')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': 'รายการเบิกจ่าย',
                'verbose_name_plural': 'รายการเบิกจ่าย',
                'ordering': ['-created_at'],
            },
        ),
    ]
