# Generated by Django 5.1.15 on 2026-02-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='ไฟล์หลักฐาน (PDF/รูปภาพ)'),
        ),
    ]
