# Generated by Django 5.1.15 on 2026-02-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_expense_receipt_file'),
        ('projects', '0010_activityreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='activity_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.activityreport', verbose_name='กิจกรรมย่อย (ครั้งที่)'),
        ),
    ]
