# Generated by Django 5.1.15 on 2026-02-23 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_expense_activity_report'),
        ('projects', '0010_activityreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('government', 'เงินแผ่นดิน'), ('accumulated', 'เงินสะสม'), ('revenue', 'เงินรายได้')], max_length=15, verbose_name='หมวดเงิน')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนเงิน')),
                ('reason', models.TextField(verbose_name='เหตุผล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('from_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='projects.activity', verbose_name='โอนจากกิจกรรม')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_transfers', to='projects.project', verbose_name='โครงการ')),
                ('to_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='projects.activity', verbose_name='โอนไปกิจกรรม')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_transfers', to=settings.AUTH_USER_MODEL, verbose_name='โอนโดย')),
            ],
            options={
                'verbose_name': 'การโอนงบประมาณ',
                'verbose_name_plural': 'การโอนงบประมาณ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expenses/attachments/', verbose_name='ไฟล์แนบ')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='ชื่อไฟล์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='อัพโหลดเมื่อ')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='budget.expense', verbose_name='รายการเบิกจ่าย')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_attachments', to=settings.AUTH_USER_MODEL, verbose_name='อัพโหลดโดย')),
            ],
            options={
                'verbose_name': 'ไฟล์แนบรายการเบิกจ่าย',
                'verbose_name_plural': 'ไฟล์แนบรายการเบิกจ่าย',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='ความเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_comments', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='budget.expense', verbose_name='รายการเบิกจ่าย')),
            ],
            options={
                'verbose_name': 'ความเห็นรายการเบิกจ่าย',
                'verbose_name_plural': 'ความเห็นรายการเบิกจ่าย',
                'ordering': ['created_at'],
            },
        ),
    ]
