# Generated by Django 5.1.15 on 2026-03-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budgettransfer_expenseattachment_expensecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget_source',
            field=models.CharField(blank=True, choices=[('government', 'เงินแผ่นดิน'), ('accumulated', 'เงินสะสม'), ('revenue', 'เงินรายได้')], max_length=20, verbose_name='แหล่งเงิน'),
        ),
    ]
