# Generated by Django 5.1.15 on 2026-02-17 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LINENotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('notification_type', models.CharField(choices=[('budget_alert', 'แจ้งเตือนงบประมาณ'), ('deadline', 'แจ้งเตือนกำหนดส่ง'), ('status_change', 'เปลี่ยนสถานะ'), ('expense_approved', 'อนุมัติรายการเบิกจ่าย')], max_length=20, verbose_name='ประเภทการแจ้งเตือน')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ส่งแล้ว')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='ส่งเมื่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.activity', verbose_name='กิจกรรมที่เกี่ยวข้อง')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='โครงการที่เกี่ยวข้อง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ประวัติการแจ้งเตือน LINE',
                'verbose_name_plural': 'ประวัติการแจ้งเตือน LINE',
                'ordering': ['-created_at'],
            },
        ),
    ]
